FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml ./
COPY api-gateway/pom.xml ./api-gateway/
COPY api-gateway/src ./api-gateway/src
RUN mvn clean package -DskipTests -f api-gateway/pom.xml

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/api-gateway/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
